export const customerFields = [
	'id',
	'customerNumber',
	'firstName',
	'lastName',
	'email',
	'company',
	'active',
	'guest',
	'birthday',
	'createdAt',
	'updatedAt',
	'groupId',
	'salesChannelId',
	'languageId',
	'salutationId',
	'defaultBillingAddressId',
	'defaultShippingAddressId',
	'defaultPaymentMethodId',
	'lastLogin',
	'orderCount',
	'orderTotalAmount',
	'addresses',
	'defaultBillingAddress',
	'defaultShippingAddress',
];

